- hosts: all
  remote_user: root

  vars:
    install_nm: false
    internal_network: 141.108.255.0/24

  tasks:
  - name: Disable selinux
    tags: setup
    selinux:
      state: disabled
  - name: Install NetworkManager
    tags: setup
    when: install_nm
    package:
      name: NetworkManager
      state: present
  - name: Enable NetworkManager
    when: install_nm
    service:
      name: NetworkManager
      state: started
      enabled: yes
  - name: Disable firewall for internal networking
    tags: networking
    iptables:
      chain: INPUT
      source: "{{internal_network}}"
      jump: ACCEPT
      action: insert
  - name: Accept mcast
    tags: networking
    iptables:
      chain: INPUT
      source: "224.0.0.18/32"
      jump: ACCEPT
      action: insert
  
- hosts: nfs
  remote_user: root

  vars:
    nfs_export_subnet: 141.108.255.0/24

  tasks:
    - name: Debug vars
      tags: nfs
      debug:
        msg: "Path to export {{nfsExportPath}}"

  roles:
    - role: geerlingguy.nfs
      nfs_exports:  ["{{nfsExportPath}} {{nfs_export_subnet}}(rw,sync,no_root_squash)"]
      tags: [ 'nfs' ]


